const test = require('node:test');
const assert = require('node:assert/strict');

test('saved report branding updates titles without changing repository names or data', () => {
  const { injectReportBranding } = require('../lib/reports/branding');
  for (const heading of ['Code Doctor コード構造監査レポート', 'Code Doctor Code Structure Audit Report']) {
    const html = `<title>Code Doctor レポート — Code Doctor repository</title><h1>${heading}</h1><pre>Code Doctor source</pre><footer>Generated by Code Doctor — date</footer>`;
    const updated = injectReportBranding(html);
    assert.match(updated, /<title>Codes Doctor — Code Doctor repository<\/title>/);
    assert.match(updated, /<h1>Codes Doctor<\/h1>/);
    assert.match(updated, /<pre>Code Doctor source<\/pre>/);
    assert.equal(injectReportBranding(updated), updated);
  }
});

test('source patches preserve literal replacement sequences in embedded libraries', () => {
  const { replaceRequired, replaceAllRequired } = require('../lib/engine/sourceReplacement');
  const literal = '$& $1 $` $\' <script>library</script>';
  assert.equal(replaceRequired('before MARKER after', 'MARKER', literal), `before ${literal} after`);
  assert.equal(replaceAllRequired('MARKER MARKER', 'MARKER', literal), `${literal} ${literal}`);
});

test('saved reports upgrade recognized libraries while preserving escaped source and other URLs', () => {
  const { upgradeReportLibraries } = require('../lib/reports/libraries');
  const source = '&lt;script src="https://cdn.jsdelivr.net/npm/marked@12/marked.min.js"&gt;&lt;/script&gt;';
  const other = '<script src="https://example.com/custom.js"></script>';
  const original = `<body>${source}${other}<script src="https://cdn.jsdelivr.net/npm/marked@12/marked.min.js"></script></body>`;
  const updated = upgradeReportLibraries(original);
  assert.ok(updated.includes(source));
  assert.ok(updated.includes(other));
  assert.ok(updated.includes('data-report-library="marked"'));
  assert.equal(upgradeReportLibraries(updated), updated);
});
