"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const settingsSchema_1 = require("../settingsSchema");
const browserLibraries_1 = require("./browserLibraries");
const reportTabs_1 = require("../reportTabs");
const reportCopy_1 = require("../reportCopy");
const markdown_1 = require("./markdown");
const sourceReplacement_1 = require("./sourceReplacement");
module.exports = function patch(source) {
    source = (0, sourceReplacement_1.replaceRequired)(source, '<meta charset="UTF-8" />', '<meta charset="UTF-8" /><meta name="codes-doctor-version" content="' + settingsSchema_1.EXTENSION_VERSION + '" />');
    source = (0, sourceReplacement_1.replaceRequired)(source, 'const repoName = node_path_1.default.basename(result.repoPath);', "const repoName = require('../html').escapeHtml(node_path_1.default.basename(result.repoPath));");
    source = (0, sourceReplacement_1.replaceRequired)(source, "mermaid.initialize({ startOnLoad: false, theme: 'default' });", "if (typeof mermaid !== 'undefined') mermaid.initialize({ startOnLoad: false, theme: 'default' });");
    source = source.replaceAll("mermaid.run({ querySelector: '#tab-graphs .mermaid' });", "if (typeof mermaid !== 'undefined') mermaid.run({ querySelector: '#tab-graphs .mermaid' });");
    const marker = '// Render initial saved Markdown results';
    if (!source.includes(marker))
        throw new Error('Markdown initialization marker missing');
    const script = `if (typeof marked !== 'undefined') { (${markdown_1.installJapaneseStrong.toString()})(marked); }`;
    source = source.replace(marker, () => '${' + JSON.stringify((script + '\n(' + (0, reportCopy_1.reviewCopySource)() + ')();').replace(/[\u3000-\u9fff]/g, (char) => '\\u' + char.charCodeAt(0).toString(16).padStart(4, '0'))) + '}\n    ' + marker);
    if (!reportTabs_1.legacyTabScript.test(source))
        throw new Error('Report tab initialization marker missing');
    source = source.replace(reportTabs_1.legacyTabScript, '');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<body>', '<body data-analysis-id="${result.analysisId}">');
    const tabScript = `<script id="${reportTabs_1.TAB_SCRIPT_ID}">(${reportTabs_1.installReportTabs.toString()})();</script>`;
    source = (0, sourceReplacement_1.replaceRequired)(source, '</body>', '${' + JSON.stringify(tabScript) + '}\n</body>');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<title>Code Doctor レポート — ${repoName}</title>', '<title>' + settingsSchema_1.PRODUCT_NAME + ' — ${repoName}</title>');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<h1>Code Doctor コード構造監査レポート</h1>', '<h1>' + settingsSchema_1.PRODUCT_NAME + '</h1>');
    source = (0, sourceReplacement_1.replaceRequired)(source, 'Generated by Code Doctor —', 'Generated by ' + settingsSchema_1.PRODUCT_NAME + ' —');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.js"></script>', '${' + JSON.stringify(browserLibraries_1.reportLibraryScripts.chart) + '}');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>', '${' + JSON.stringify(browserLibraries_1.reportLibraryScripts.mermaid) + '}');
    source = (0, sourceReplacement_1.replaceRequired)(source, '<script src="https://cdn.jsdelivr.net/npm/marked@12/marked.min.js"></script>', '${' + JSON.stringify(browserLibraries_1.reportLibraryScripts.marked) + '}');
    return source;
};
