"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.injectReportBranding = injectReportBranding;
const settingsSchema_1 = require("../settingsSchema");
/** Update report-owned headings without rewriting repository names or report data. */
function injectReportBranding(html) {
    return html
        .replace(/(<title>)Code Doctor(?: レポート| Report)?(?=\s*[—-]|<)/i, (_match, prefix) => prefix + settingsSchema_1.PRODUCT_NAME)
        .replace(/<h1>Code Doctor(?: コード構造監査レポート| Code Structure Audit Report)?<\/h1>/i, () => '<h1>' + settingsSchema_1.PRODUCT_NAME + '</h1>')
        .replace(/(<footer>)Generated by Code Doctor —/i, (_match, prefix) => prefix + 'Generated by ' + settingsSchema_1.PRODUCT_NAME + ' —');
}
