import { PRODUCT_NAME, EXTENSION_VERSION } from '../settingsSchema';
import { reportLibraryScripts } from './browserLibraries';
import { installReportTabs, TAB_SCRIPT_ID, legacyTabScript } from '../reportTabs';
import { reviewCopySource } from '../reportCopy';
import { installJapaneseStrong } from './markdown';
import { replaceRequired } from './sourceReplacement';

module.exports = function patch(source: string) {
    source = replaceRequired(source, '<meta charset="UTF-8" />', '<meta charset="UTF-8" /><meta name="codes-doctor-version" content="' + EXTENSION_VERSION + '" />');
    source = replaceRequired(source, 'const repoName = node_path_1.default.basename(result.repoPath);', "const repoName = require('../html').escapeHtml(node_path_1.default.basename(result.repoPath));");
    source = replaceRequired(source, "mermaid.initialize({ startOnLoad: false, theme: 'default' });", "if (typeof mermaid !== 'undefined') mermaid.initialize({ startOnLoad: false, theme: 'default' });");
    source = source.replaceAll("mermaid.run({ querySelector: '#tab-graphs .mermaid' });", "if (typeof mermaid !== 'undefined') mermaid.run({ querySelector: '#tab-graphs .mermaid' });");
    const marker = '// Render initial saved Markdown results';
    if (!source.includes(marker)) throw new Error('Markdown initialization marker missing');
    const script = `if (typeof marked !== 'undefined') { (${installJapaneseStrong.toString()})(marked); }`;
    source = source.replace(marker, () => '${' + JSON.stringify((script + '\n(' + reviewCopySource() + ')();').replace(/[\u3000-\u9fff]/g, (char: string) => '\\u' + char.charCodeAt(0).toString(16).padStart(4, '0'))) + '}\n    ' + marker);

  if (!legacyTabScript.test(source)) throw new Error('Report tab initialization marker missing');
  source = source.replace(legacyTabScript, '');
  source = replaceRequired(source, '<body>', '<body data-analysis-id="${result.analysisId}">');
  const tabScript = `<script id="${TAB_SCRIPT_ID}">(${installReportTabs.toString()})();</script>`;
  source = replaceRequired(source, '</body>', '${' + JSON.stringify(tabScript) + '}\n</body>');
  source = replaceRequired(source, '<title>Code Doctor レポート — ${repoName}</title>', '<title>' + PRODUCT_NAME + ' — ${repoName}</title>');
  source = replaceRequired(source, '<h1>Code Doctor コード構造監査レポート</h1>', '<h1>' + PRODUCT_NAME + '</h1>');
  source = replaceRequired(source, 'Generated by Code Doctor —', 'Generated by ' + PRODUCT_NAME + ' —');
  source = replaceRequired(source, '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.js"></script>', '${' + JSON.stringify(reportLibraryScripts.chart) + '}');
  source = replaceRequired(source, '<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>', '${' + JSON.stringify(reportLibraryScripts.mermaid) + '}');
  source = replaceRequired(source, '<script src="https://cdn.jsdelivr.net/npm/marked@12/marked.min.js"></script>', '${' + JSON.stringify(reportLibraryScripts.marked) + '}');
  return source;
};

export {};
