import { PRODUCT_NAME } from '../settingsSchema';
/** Update report-owned headings without rewriting repository names or report data. */
export function injectReportBranding(html: string): string {
  return html
    .replace(/(<title>)Code Doctor(?: レポート| Report)?(?=\s*[—-]|<)/i, (_match: string, prefix: string) => prefix + PRODUCT_NAME)
    .replace(/<h1>Code Doctor(?: コード構造監査レポート| Code Structure Audit Report)?<\/h1>/i, () => '<h1>' + PRODUCT_NAME + '</h1>')
    .replace(/(<footer>)Generated by Code Doctor —/i, (_match: string, prefix: string) => prefix + 'Generated by ' + PRODUCT_NAME + ' —');
}
